# Schema for the configuration files of the Launchdarkly module.
launchdarkly.settings:
  type: config_object
  label: 'Launchdarkly settings'
  mapping:
    launchdarkly_sdk_key:
      type: string
      label: 'LaunchDarkly SDK Key'
